name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Cache Hardhat compiler
        uses: actions/cache@v3
        with:
          path: ~/.cache/hardhat-nodejs/solc
          key: ${{ runner.os }}-solc-0.8.20
      - name: Install deps & compile
        run: |
          npm install
          npx hardhat compile
      - name: Run tests
        run: npm test
